red/green: Added test to deduct balance and added code to pass:
MerylRatallsAir:oystercard mrastall$ rspec
...F

Failures:

  1) Oystercard#deduct() deducts an amount from the balance
     Failure/Error: @blance -= value

     NoMethodError:
       undefined method `-' for nil:NilClass
     # ./lib/oystercard.rb:19:in `deduct'
     # ./spec/oystercard_spec.rb:22:in `block (4 levels) in <top (required)>'
     # ./spec/oystercard_spec.rb:22:in `block (3 levels) in <top (required)>'

Finished in 0.02116 seconds (files took 0.22788 seconds to load)
4 examples, 1 failure

Failed examples:

rspec ./spec/oystercard_spec.rb:20 # Oystercard#deduct() deducts an amount from the balance

MerylRatallsAir:oystercard mrastall$ rspec
....

Finished in 0.01934 seconds (files took 0.22127 seconds to load)
4 examples, 0 failures