RED: Added test to check that new oystercards have a balance of 0 when initialized
F

Failures:

  1) Oystercard initialized cards freshly initialized cards should have a balance of 0
     Failure/Error: expect(subject.balance).to eq 0

     NoMethodError:
       undefined method `balance' for #<Oystercard:0x00007fbed89a2f38>
     # ./spec/oystercard_spec.rb:5:in `block (3 levels) in <top (required)>'

Finished in 0.00233 seconds (files took 0.09511 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/oystercard_spec.rb:4 # Oystercard initialized cards freshly initialized cards should have a balance of 0