RED/GREEN: added top_up tests and code passing tests
.F

Failures:

  1) Oystercard#top_up tops up the balance by value
     Failure/Error: expect { subject.top_up(10) }.to change { subject.balance }.by 10

     NoMethodError:
       undefined method `top_up' for #<Oystercard:0x00007f930681f470 @balance=0>
     # ./spec/oystercard_spec.rb:11:in `block (4 levels) in <top (required)>'
     # ./spec/oystercard_spec.rb:11:in `block (3 levels) in <top (required)>'

Finished in 0.0105 seconds (files took 0.16235 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/oystercard_spec.rb:10 # Oystercard#top_up tops up the balance by value

➜  oystercard git:(master) ✗ rspec
.F

Failures:

  1) Oystercard#top_up tops up the balance by value
     Failure/Error:
       def top_up
       end

     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./lib/oystercard.rb:7:in `top_up'
     # ./spec/oystercard_spec.rb:11:in `block (4 levels) in <top (required)>'
     # ./spec/oystercard_spec.rb:11:in `block (3 levels) in <top (required)>'

Finished in 0.00492 seconds (files took 0.10024 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/oystercard_spec.rb:10 # Oystercard#top_up tops up the balance by value

➜  oystercard git:(master) ✗ rspec
.F

Failures:

  1) Oystercard#top_up tops up the balance by value
     Failure/Error: expect { subject.top_up(10) }.to change { subject.balance }.by 10
       expected `subject.balance` to have changed by 10, but was changed by 0
     # ./spec/oystercard_spec.rb:11:in `block (3 levels) in <top (required)>'

Finished in 0.03494 seconds (files took 0.08905 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/oystercard_spec.rb:10 # Oystercard#top_up tops up the balance by value

➜  oystercard git:(master) ✗ rspec
..

Finished in 0.0048 seconds (files took 0.09004 seconds to load)
2 examples, 0 failures