RED/GREEN: Added station class and tests
..........F

Failures:

  1) Station responds to station name
     Failure/Error: expect(station).to respond_to(:name)

     NameError:
       undefined local variable or method `station' for #<RSpec::ExampleGroups::Station:0x00007fac87965060>
     # ./spec/station_spec.rb:4:in `block (2 levels) in <top (required)>'

Finished in 0.00816 seconds (files took 0.09425 seconds to load)
11 examples, 1 failure

Failed examples:

rspec ./spec/station_spec.rb:3 # Station responds to station name

➜  oystercard git:(master) ✗ rspec
............

Finished in 0.01761 seconds (files took 0.13524 seconds to load)
12 examples, 0 failures