red/green: Added unit test for touch in method. Added code to pass test
MerylRatallsAir:oystercard mrastall$ rspec
.....F

Failures:

  1) Oystercard#touch_in updat4es @travelling? to true
     Failure/Error: subject.touch_in

     NoMethodError:
       undefined method `touch_in' for #<Oystercard:0x00007fc013a30d38 @balance=0>
     # ./spec/oystercard_spec.rb:35:in `block (3 levels) in <top (required)>'

Finished in 0.02313 seconds (files took 0.22655 seconds to load)
6 examples, 1 failure

Failed examples:

rspec ./spec/oystercard_spec.rb:34 # Oystercard#touch_in updat4es @travelling? to true

MerylRatallsAir:oystercard mrastall$ rspec

An error occurred while loading ./spec/oystercard_spec.rb.
Failure/Error: require './lib/oystercard'

SyntaxError:
  /Users/mrastall/Documents/makers_work/week2/oystercard_beca/oystercard/lib/oystercard.rb:7: syntax error, unexpected '='
      @travelling? = false
                   ^
  /Users/mrastall/Documents/makers_work/week2/oystercard_beca/oystercard/lib/oystercard.rb:26: syntax error, unexpected `end'
    end
    ^~~
  /Users/mrastall/Documents/makers_work/week2/oystercard_beca/oystercard/lib/oystercard.rb:29: syntax error, unexpected '='
      @travelling? = true
                   ^
  /Users/mrastall/Documents/makers_work/week2/oystercard_beca/oystercard/lib/oystercard.rb:32: syntax error, unexpected end-of-input, expecting `end'
No examples found.

Finished in 0.00006 seconds (files took 0.25197 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

MerylRatallsAir:oystercard mrastall$ rspec
......

Finished in 0.02288 seconds (files took 0.21948 seconds to load)
6 examples, 0 failures